# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0003_auto_20171019_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='bookreview.Author'),
        ),
    ]
